# this file will be overwritten via github secret
# environment files are in notion page
# if, it needed to be modified set `APPLICATION_YML` in github secret with base64 encoding
spring:
  application:
    name: more
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:more
    username: sa
    password:
